### PR TITLE
Branch bug fix add command

### LINKED ISSUE #102: [Bug] Add command incorrectly accepts t/ tag parameter
The add command currently accepts the t/ parameter for adding tags directly, which conflicts with our application's design. Tags should only be added through dedicated commands like `addsubject` and `addsession`, not through the general t/ parameter in the add command.

Image

### PR DESCRIPTION
**Pull request by TeeJinSeng**
Closes #102, #128, #111, #107
- remove `/t` for `add` command
- set the maximum length for name to 50
- set the maximum length for email to 100(based on record holder of longest functioning email)
- set the maximum length for address to 70
- duplicate names are now allowed
- name argument now accept all the `/` not recognized as an argument

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -48,7 +48,7 @@ public AddCommand parse(String args) throws ParseException {
         Phone phone = ParserUtil.parsePhone(argMultimap.getValue(PREFIX_PHONE).get());
         Email email = ParserUtil.parseEmail(argMultimap.getValue(PREFIX_EMAIL).get());
         Address address = ParserUtil.parseAddress(argMultimap.getValue(PREFIX_ADDRESS).get());
-        Set<Tag> tagList = ParserUtil.parseTags(argMultimap.getAllValues(PREFIX_TAG));
+        Set<Tag> tagList = ParserUtil.parseTags(List.of());
```
Comment (mackerelsoup) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Wont this create an empty list instead of taking the list of tags

**Review by mackerelsoup — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java (hunk 1 above)
Comment (TeeJinSeng) [reply src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Ya it will create a new person with no tags, because we are not accepting `/t` anymore so the person should not be added any tags based on user's input
