### PR TITLE
Branch fix edit test ordering

### LINKED ISSUE #132: EditCommandTest has a chance to fail sometimes
When running unit tests, execute_editBothSessionsAndSubjects_success() in EditCommandTest has a small chance to fail, but passes majority of the time

Image

How to replicate: keep rerunning all tests in tp.test until failure is observed

Running execute_editBothSessionsAndSubjects_success() in isolation seems to always pass

### PR DESCRIPTION
**Pull request by ZavierCSJ**
closes #132

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 1]
```diff
@@ -128,6 +128,34 @@ public static void assertCommandFailure(Command command, Model actualModel, Stri
...
+     * @param actualModel the model to execute the command on
+     * @param expectedPerson the expected Person after command execution
+     * @param expectedModel the expected model state after command execution
+     */
+    public static void assertCommandSuccessWithOrderIndependentComparison(Command command, Model actualModel,
+            Person expectedPerson, Model expectedModel) {
+        try {
+            CommandResult result = command.execute(actualModel);
+            // Verify the command success message starts correctly (ignoring tag order in string)
+            assertTrue(result.getFeedbackToUser().startsWith("Edited Person:"));
```
Comment (kbyeo) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: Follows testing conventions
